### ISSUE TITLE
Word embedding file

### ISSUE THREAD

**Issue by sohamparikh94** [malllabiisc/DiPS#1]
I downloaded the Google word vectors bin file and placed it inside `data`, but I encountered a `No such file or directory: 'data/embeddings/word2vec.pickle'` while trying to train the model

**Comment by ashutoshml** [comment]
Hi @sohamparikh94 ,

The `word2vec.pickle` file is generated using `create_dict.py`. Please see the updated README for details.

**Comment by sohamparikh94** [comment]
I tried running `create_dict.py` but it looks like the error comes from an import statement

`python -m src.create_dict -model pretrained -run_name something -gpu 0


Loading Word2Vec
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/code/DiPS/src/create_dict.py", line 15, in <module>
    from src.model import s2s
  File "/home/ubuntu/code/DiPS/src/model.py", line 15, in <module>
    from submodopt.submodopt import SubmodularOpt
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/submodopt-0.1.0-py3.7.egg/submodopt/submodopt.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/submodopt-0.1.0-py3.7.egg/submodopt/submodular_funcs.py", line 24, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'data/embeddings/word2vec.pickle'`

**Comment by ashutoshml** [comment]
Hi @sohamparikh94 

Thanks for pointing this out. Please pull the latest version and re-install package submodopt

```shell
$ cd ./packages/submodopt
$ python setup.py install
$ cd ../../
```

Let me know if you face any more issues.

**Comment by sohamparikh94** [comment]
This fixes it! Thanks a lot for your help @ashutoshml
