### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by DeepMehta-DM** [malllabiisc/DiPS#17]
Hi, firstly thank you very much for the code and detailed explanation. 

I am running this line of code: 
`! python -m src.main -mode train -gpu 0 -use_attn -bidirectional -dataset twitter -run_name DiPS`

and I am getting following error:
Loading Word2Vec
Word2vec Loaded
Time Taken : 0.0016974012056986492
2020-06-07 22:22:12,866 | INFO | __main__ | Training and Validation data loading..
2020-06-07 22:22:13,243 | INFO | __main__ | Training and Validation data loaded!
2020-06-07 22:22:13,243 | INFO | __main__ | Creating vocab ...
2020-06-07 22:22:30,206 | INFO | __main__ | Vocab created with number of words = 18865
2020-06-07 22:22:30,207 | INFO | __main__ | Saving Vocabulary file
2020-06-07 22:22:30,217 | INFO | __main__ | Vocabulary file saved in Model/DiPS/vocab.p
2020-06-07 22:22:30,219 | INFO | __main__ | Checkpoint found with epoch num 30
2020-06-07 22:22:30,297 | INFO | __main__ | Building Encoder RNN..
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/drive/My Drive/Colab Notebooks/DiPS/src/main.py", line 473, in <module>
    main()
  File "/content/drive/My Drive/Colab Notebooks/DiPS/src/main.py", line 415, in main
    model = s2s(args, voc, device, logger)
  File "/content/drive/My Drive/Colab Notebooks/DiPS/src/model.py", line 44, in __init__
    self.config.bidirectional).to(device)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 386, in to
    return self._apply(convert)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/rnn.py", line 127, in _apply
    self.flatten_parameters()
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/rnn.py", line 123, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

Actually, I am using colab for training and I trained for 12 hours and it went upto 74 epochs with defaults. Although in my drive I could see the last file of 30th epoch. So i thought of restarting it last night and it resumed from 30th epoch. But due to some reason I had to stop after 4 epochs and I stopped the code and switched off. But now when I am running the whole thing same way again today, I am unable to proceed with training and getting this error. Please help. I am just a newbie in this field.

**Comment by ashutoshml** [comment]
@DeepMehta-DM 
This is more of a CUDA/CUDNN issue than the code. 
There probably can be multiple reasons for this. Please look at PyTorch forums for a resolution.
